### PR TITLE
Add xproto module

### PR DESCRIPTION
**Pull request by jespino**
I have reviewed all variables to have the type expected by the C Api functions, and works with my own project (github.com/rustmore/rumenu).

### CODE REVIEW

**Comment by robertknight** [comment]
This PR duplicates some of the constants that are already defined in the 'xlib' module but doesn't include the structs from Xproto.h - that might make it difficult for other people using this package to know where to find constants and functions when looking at the Rust documentation or translating existing C code snippets (from blogs, StackOverflow, existing GitHub projects etc.) using X11 headers to Rust code using x11-rs.

My suggestion would be to have one Rust module per 'public' X11 header (eg. Xproto.h -> xproto, Xlib.h -> xlib, X.h -> x) with the same structs, functions and constants. These could be auto-generated in many cases. Thoughts @Daggerbot ?

**Comment by jespino** [comment]
I'm agree, I have to rewrite it to split the xproto, I think this must be xproto::xproto, xproto::x, xproto::xatom... etcetera.

Anyway there are some duplication between xproto and xlib because are independent packages, and X.h from xproto package have constants from the Xlib package, this means that for coherence, this must be duplicated, ins't it?

**Comment by robertknight** [comment]
> I'm agree, I have to rewrite it to split the xproto, I think this must be
> xproto::xproto, xproto::x, xproto::xatom... etcetera.

By 'package' do you mean Debian/Ubuntu/Red Hat packages? On my system there is just one X.h file, perhaps I misunderstand?

I was thinking more along the lines of `/usr/include/X11/<foo>.h` => `<foo>` (so just 'x11::x' rather than 'x11::xproto::x'). The idea being that a code snippet beginning with:

```
#include <X11/X.h>
#include <X11/Xproto.h>
...
```

Could be easily translated into Rust as:

```
use x11::x;
use x11::xproto;
```

**Comment by jespino** [comment]
I'm using the http://cgit.freedesktop.org/xorg/proto/xproto/ repository as base for the xproto, then I'm think in this like an indpendent package (I don't have a good knowledge about X11 C library, I'm learning it while I create my project, and when I needed extra constants I tried to find the better way to include it :disappointed: )

Anyway, knowing that the base of the code used must be my system /usr/include/X11, I think I can retry it.

Thanks for your patient and the info :)

**Comment by jespino** [comment]
Then, I'm thinking that some variables from xlib.rs must moved to x.rs, ins't it? mainly all the X.h constants. It's correct?

**Comment by jespino** [comment]
I'm going to close this PR and open probably other 2. One for include in the xlib.rs all the X.h constants, and one with the Xproto.h structures and constants.

Thanks for your help @robertknight

**Pull request closed without merging**
